package spielpackage;

import Classes.MyDB;
import Classes.Frame;
import Classes.spielerDB;
import databasepackage.AnmeldenFrame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alwai
 */
public class startseite extends javax.swing.JFrame {

    /**
     * Creates new form startseite
     */
    public startseite() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage();
        BackgroundMines();
        BackgroundPlus();
        Verkleinern();
        MyDatei();
        //DB_AktualisierenSeiter();
    }

    JFrame frame;
    Frame window = new Frame("/Icons/FrimeIcon.png");
    Frame Finster = new Frame();

    AnmeldenFrame anmelden = new AnmeldenFrame();

    spielerDB sdb = new spielerDB();
    ResultSet rs;
    Connection con;
    Statement stmt;
    String Username;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        DB_AktualisierenMenu = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        max = new javax.swing.JMenuItem();
        verkleinern = new javax.swing.JMenuItem();
        min = new javax.swing.JMenuItem();
        hineinzoomen = new javax.swing.JMenuItem();
        rauszoomen = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONNECT 4");
        setSize(new java.awt.Dimension(882, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Background.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 29, 940, 520));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/hintergrund2.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(898, 515));
        jLabel1.setPreferredSize(new java.awt.Dimension(898, 515));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1110, -100, 3010, 2000));

        jMenu1.setText("Datei");

        DB_AktualisierenMenu.setText("DB Aktualisieren");
        DB_AktualisierenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DB_AktualisierenMenuActionPerformed(evt);
            }
        });
        jMenu1.add(DB_AktualisierenMenu);

        jMenuItem1.setText("Ausloggen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bearbeiten");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenu5.setText("jMenu5");

        buttonGroup1.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("50%");
        jMenu5.add(jRadioButtonMenuItem1);

        buttonGroup1.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("100%");
        jMenu5.add(jRadioButtonMenuItem2);

        buttonGroup1.add(jRadioButtonMenuItem3);
        jRadioButtonMenuItem3.setText("150%");
        jMenu5.add(jRadioButtonMenuItem3);

        buttonGroup1.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("200%");
        jMenu5.add(jRadioButtonMenuItem4);

        buttonGroup1.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("300%");
        jMenu5.add(jRadioButtonMenuItem6);

        buttonGroup1.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("full screan");
        jMenu5.add(jRadioButtonMenuItem5);

        jMenu3.add(jMenu5);

        max.setText("Maximieren");
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        jMenu3.add(max);

        verkleinern.setText("Verkleinern");
        verkleinern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verkleinernActionPerformed(evt);
            }
        });
        jMenu3.add(verkleinern);

        min.setText("Minimieren");
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        jMenu3.add(min);

        hineinzoomen.setText("Hineinzoomen");
        hineinzoomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hineinzoomenActionPerformed(evt);
            }
        });
        jMenu3.add(hineinzoomen);

        rauszoomen.setText("Rauszoomen");
        rauszoomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rauszoomenActionPerformed(evt);
            }
        });
        jMenu3.add(rauszoomen);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Hife");

        jMenuItem2.setText("About");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1059, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackgroundMines() {
        Finster.Bereit = getSize().width - 150;
        Finster.Lang = getSize().height - 75;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void protzent50() {
        getSize().width = getSize().width + 150;
        getSize().height = 75;
        this.setSize(getSize().width, getSize().height);
        setLocationRelativeTo(null);
    }

    private void protzent100() {
        getSize().width = 150;
        getSize().height = 75;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void protzent150() {
        getSize().width = 150;
        getSize().height = 75;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void protzent200() {
        getSize().width = 150;
        getSize().height = 75;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void protzent300() {
        getSize().width = 150;
        getSize().height = 75;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void BackgroundPlus() {
        Finster.Bereit = getSize().width + 150;
        Finster.Lang = getSize().height + 75;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void Verkleinern() {
        Finster.Bereit = 1227;
        Finster.Lang = 708;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    private void MyDatei() {

        try {
            MyDB db = new MyDB();
            con = DriverManager.getConnection(db.host, db.uname, db.pass);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(db.SQL);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /*
    private void DB_AktualisierenSeiter() {
        try {
            if ("root".equals(anmelden.user_suchen)) {
                DB_AktualisierenMenu.setEnabled(true);
                JOptionPane.showMessageDialog(null, "DONE");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frame = new JFrame("EXIT");
        if (JOptionPane.showConfirmDialog(frame, "Bestätigen Sie, ob Sie Ausloggen möchten", "CONNECT 4",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        this.setExtendedState(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_minActionPerformed

    private void hineinzoomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hineinzoomenActionPerformed
        protzent50();
    }//GEN-LAST:event_hineinzoomenActionPerformed

    private void rauszoomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rauszoomenActionPerformed
        BackgroundMines();
    }//GEN-LAST:event_rauszoomenActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_maxActionPerformed

    private void verkleinernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verkleinernActionPerformed
        protzent50();
    }//GEN-LAST:event_verkleinernActionPerformed

    private void DB_AktualisierenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DB_AktualisierenMenuActionPerformed

    }//GEN-LAST:event_DB_AktualisierenMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startseite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startseite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startseite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startseite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startseite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem DB_AktualisierenMenu;
    public static javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JMenuItem hineinzoomen;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JMenu jMenu1;
    public static javax.swing.JMenu jMenu2;
    public static javax.swing.JMenu jMenu3;
    public static javax.swing.JMenu jMenu4;
    public static javax.swing.JMenu jMenu5;
    public static javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    public static javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    public static javax.swing.JMenuItem max;
    public static javax.swing.JMenuItem min;
    public static javax.swing.JMenuItem rauszoomen;
    public static javax.swing.JMenuItem verkleinern;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(window.icon.toString())));
    }

}
