package databasepackage;

import spielpackage.startseite;

import Classes.MyDB;
import Classes.Frame;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alwai
 */
public class AnmeldenFrame extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;

    KontoErstellenFrame kontoerstellen;
    startseite start;

    Frame window = new Frame("/Icons/FrimeIcon.png");

    public String user_suchen;
    String pass_suchen;

    /**
     * Creates new form anmeldenseite
     */
    public AnmeldenFrame() {
        initComponents();
        setLocationRelativeTo(null);
        MyDatei();
        setIconImage();
        VariabelDiklarieren();

    }

    Frame[] PassZeigerIcon = new Frame[2];
    Frame[] EMM = new Frame[6];
    private JFrame frame;
    Frame Finster = new Frame();

    private void MyDatei() {
        try {
            MyDB db = new MyDB();
            con = DriverManager.getConnection(db.host, db.uname, db.pass);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(db.SQL);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void VariabelDiklarieren() {
        // Exit, Minimeren, Maximieren Icons Deklarieren
        EMM[0] = new Frame("/Icons/exiticon2.jpg");
        EMM[1] = new Frame("/Icons/exiticon.png");

        EMM[2] = new Frame("/Icons/minimieren.jpg");
        EMM[3] = new Frame("/Icons/minusicon.png");

        EMM[4] = new Frame("/Icons/maximieren.jpg");
        EMM[5] = new Frame("/Icons/verkleinernicon.png");
        // End of Exit, Min, Max Deklariern
        // Password Zeiger Icon Deklarieren
        PassZeigerIcon[0] = new Frame("/Icons/show.png");
        PassZeigerIcon[1] = new Frame("/Icons/do_not_show.png");
        PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[0].icon.toString())));
        // End of Password Deklariern
    }

    private void Verkleinern() {
        Finster.Bereit = 1260;
        Finster.Lang = 702;
        this.setSize(Finster.Bereit, Finster.Lang);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        KontoErstellen = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AnmeldenButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        PassVergessen = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        PassZeigen = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        UserField3 = new javax.swing.JTextField();
        jPanel47 = new javax.swing.JPanel();
        MaximierenPanel = new javax.swing.JPanel();
        max = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        VerkleinernPanel = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0,0,0,120));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserIcon.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ALWAIS'S SPIEL");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HABEN SIE KEIN KONTO?");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        KontoErstellen.setBackground(new java.awt.Color(0, 0, 0,0));
        KontoErstellen.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        KontoErstellen.setForeground(new java.awt.Color(51, 51, 51));
        KontoErstellen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        KontoErstellen.setText("KONTO ERSTELLEN");
        KontoErstellen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KontoErstellenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KontoErstellenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KontoErstellenMouseExited(evt);
            }
        });
        jPanel12.add(KontoErstellen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 390, 670));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153,80));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnmeldenButton.setBackground(new java.awt.Color(0, 102, 153));
        AnmeldenButton.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        AnmeldenButton.setForeground(new java.awt.Color(255, 255, 255));
        AnmeldenButton.setText("ANMELDEN");
        AnmeldenButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        AnmeldenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AnmeldenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AnmeldenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnmeldenButtonActionPerformed(evt);
            }
        });
        jPanel4.add(AnmeldenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 280, 70));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        PassVergessen.setBackground(new java.awt.Color(0, 0, 0,0));
        PassVergessen.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        PassVergessen.setForeground(new java.awt.Color(51, 51, 51));
        PassVergessen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassVergessen.setText("PASSWORD VERGESSEN");
        PassVergessen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PassVergessenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PassVergessenMouseExited(evt);
            }
        });
        jPanel7.add(PassVergessen);

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 220, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255,0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "WILLKOMMEN ZURÜCK!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Traditional Arabic", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("WIR FREUEN UNS SEHR, SIE WIEDERZUSEHEN");
        jPanel8.add(jLabel8);

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 630, 190));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 204));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/passwordField.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2);

        PasswordField1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        PasswordField1.setForeground(new java.awt.Color(0, 102, 153));
        PasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PASSWORD:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        PasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordField1MouseClicked(evt);
            }
        });
        PasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField1ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        PassZeigen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassZeigen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/show.png"))); // NOI18N
        PassZeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassZeigenActionPerformed(evt);
            }
        });
        jPanel6.add(PassZeigen);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 500, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setForeground(new java.awt.Color(0, 0, 204));
        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/usernameField.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel7);

        UserField3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        UserField3.setForeground(new java.awt.Color(0, 102, 153));
        UserField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserField3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USERNAME: ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        UserField3.setMinimumSize(new java.awt.Dimension(15, 45));
        UserField3.setPreferredSize(new java.awt.Dimension(15, 45));
        UserField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserField3MouseClicked(evt);
            }
        });
        UserField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserField3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UserField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 500, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 870, 670));

        jPanel47.setBackground(new java.awt.Color(0, 0, 0));
        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        MaximierenPanel.setBackground(new java.awt.Color(255, 255, 255));
        MaximierenPanel.setEnabled(false);
        MaximierenPanel.setLayout(new java.awt.GridLayout());

        max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/verkleinernicon.png"))); // NOI18N
        max.setBorder(null);
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });
        MaximierenPanel.add(max);

        ExitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExitPanel.setLayout(new java.awt.GridLayout());

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exiticon.png"))); // NOI18N
        exit.setBorder(null);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        ExitPanel.add(exit);

        VerkleinernPanel.setBackground(new java.awt.Color(255, 255, 255));
        VerkleinernPanel.setLayout(new java.awt.GridLayout());

        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minusicon.png"))); // NOI18N
        min.setBorder(null);
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        VerkleinernPanel.add(min);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/conect422.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("CONNECT 4");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addComponent(ExitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VerkleinernPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MaximierenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 938, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(VerkleinernPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MaximierenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/AnmeldenHintergrund_1.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        setSize(new java.awt.Dimension(1260, 702));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void AnmeldenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnmeldenButtonActionPerformed

        try {
            if (UserField3.getText().isEmpty() || PasswordField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "USERNAME UND PASSWORD EINGEBEN!", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
            } else {
                user_suchen = UserField3.getText();
                pass_suchen = PasswordField1.getText();

                boolean found = false;
                rs.absolute(0);
                while (rs.next()) {

                    if (user_suchen.equals(rs.getString(3))) {
                        found = true;

                        if (!pass_suchen.equals(rs.getString(4))) {
                            JOptionPane.showMessageDialog(this, "FALSCHES PASSWORD!", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
                            PasswordField1.setText("");
                            break;
                        } else {
                            start = new startseite();
                            start.setVisible(true);
                            this.setVisible(false);
                        }
                    }
                }
                if (found == false) {
                    JOptionPane.showMessageDialog(this, "DAS CONNECT4-KONTO WURDE NICHT GEFUNDEN!", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
                    PasswordField1.setText("");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_AnmeldenButtonActionPerformed

    private void PasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField1ActionPerformed

        try {
            if (UserField3.getText().isEmpty() || PasswordField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "USERNAME UND PASSWORD EINGEBEN!", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
            } else {
                user_suchen = UserField3.getText();
                pass_suchen = PasswordField1.getText();

                boolean found = false;
                rs.absolute(0);
                while (rs.next()) {

                    if (user_suchen.equals(rs.getString(3))) {
                        found = true;

                        if (!pass_suchen.equals(rs.getString(4))) {
                            JOptionPane.showMessageDialog(this, "FALSCHES PASSWORD!", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
                            PasswordField1.setText("");
                            break;
                        } else {
                            start = new startseite();
                            start.setVisible(true);
                            this.setVisible(false);
                        }
                    }
                }
                if (found == false) {
                    JOptionPane.showMessageDialog(this, "DAS CONNECT4-KONTO WURDE NICHT GEFUNDEN!", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
                    PasswordField1.setText("");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_PasswordField1ActionPerformed

    private void PassZeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassZeigenActionPerformed
        // TODO add your handling code here:
        if (PassZeigen.isSelected()) {
            PasswordField1.setEchoChar((char) 0);
            PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[1].icon.toString())));
        } else {
            PasswordField1.setEchoChar('*');
            PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[0].icon.toString())));
        }
    }//GEN-LAST:event_PassZeigenActionPerformed

    private void PassVergessenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassVergessenMouseEntered
        // TODO add your handling code here:
        PassVergessen.setForeground(new java.awt.Color(0, 153, 255));
    }//GEN-LAST:event_PassVergessenMouseEntered

    private void PassVergessenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassVergessenMouseExited
        // TODO add your handling code here:
        PassVergessen.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_PassVergessenMouseExited

    private void PasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordField1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField1MouseClicked

    private void UserField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserField3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UserField3MouseClicked

    private void UserField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserField3ActionPerformed

    private void KontoErstellenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KontoErstellenMouseEntered
        // TODO add your handling code here:
        KontoErstellen.setForeground(new java.awt.Color(0, 153, 255));
    }//GEN-LAST:event_KontoErstellenMouseEntered

    private void KontoErstellenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KontoErstellenMouseExited
        // TODO add your handling code here:
        KontoErstellen.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_KontoErstellenMouseExited

    private void KontoErstellenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KontoErstellenMouseClicked
        // TODO add your handling code here:
        kontoerstellen = new KontoErstellenFrame();
        kontoerstellen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_KontoErstellenMouseClicked

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        // TODO add your handling code here:
        /*  if (getSize().width > 1260 && getSize().height > 702) {
            Verkleinern();
        } else {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        */
    }//GEN-LAST:event_maxMouseClicked

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[0].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[2].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[4].icon.toString())));
        MaximierenPanel.setBackground(Color.GREEN);
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        MaximierenPanel.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_maxMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        frame = new JFrame("EXIT");

        if (JOptionPane.showConfirmDialog(frame, "Bestätigen Sie, ob Sie beenden möchten", "CONNECT 4",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[0].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[2].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[4].icon.toString())));
        ExitPanel.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        ExitPanel.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_exitMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[0].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[2].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[4].icon.toString())));
        VerkleinernPanel.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        VerkleinernPanel.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_minMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnmeldenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnmeldenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnmeldenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnmeldenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnmeldenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AnmeldenButton;
    public javax.swing.JPanel ExitPanel;
    public javax.swing.JLabel KontoErstellen;
    public javax.swing.JPanel MaximierenPanel;
    public javax.swing.JLabel PassVergessen;
    public javax.swing.JCheckBox PassZeigen;
    public javax.swing.JPasswordField PasswordField1;
    public javax.swing.JTextField UserField3;
    public javax.swing.JPanel VerkleinernPanel;
    public javax.swing.JLabel exit;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel12;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel47;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JLabel max;
    public javax.swing.JLabel min;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(window.icon.toString())));
    }

}
