/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databasepackage;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Classes.MyDB;
import Classes.Frame;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author alwai
 */
public class KontoErstellenFrame extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    PreparedStatement ss;
    private JFrame frame;
    AnmeldenFrame Anmelden;
    int updateStatement;

    MyDB db = new MyDB();
    AnmeldenFrame anmelden;

    Frame window = new Frame("/Icons/FrimeIcon.png");
    Frame[] PassZeigerIcon = new Frame[2];
    Frame[] EMM = new Frame[6];

    /**
     * Creates new form KontoErstellenFrame
     */
    public KontoErstellenFrame() {
        initComponents();
        setLocationRelativeTo(null);
        MyDatei();
        setIconImage();
        VariabelDiklarieren();
    }

    private void MyDatei() {
        try {

            con = DriverManager.getConnection(db.host, db.uname, db.pass);
            stmt = con.createStatement();
            ss = con.prepareStatement("INSERT INTO CONNECT4SPIELER (NACHNAME, VORNAME, USERNAME, PASSWORD) VALUES ( ?,?,?,?)");
            rs = stmt.executeQuery(db.SQL);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void VariabelDiklarieren() {
        // Exit, Minimeren, Maximieren Icons Deklarieren
        EMM[0] = new Frame("/Icons/exiticon2.jpg");
        EMM[1] = new Frame("/Icons/exiticon.png");

        EMM[2] = new Frame("/Icons/minimieren.jpg");
        EMM[3] = new Frame("/Icons/minusicon.png");

        EMM[4] = new Frame("/Icons/maximieren.jpg");
        EMM[5] = new Frame("/Icons/verkleinernicon.png");
        // End of Exit, Min, Max Deklariern
        // Password Zeiger Icon Deklarieren
        PassZeigerIcon[0] = new Frame("/Icons/show.png");
        PassZeigerIcon[1] = new Frame("/Icons/do_not_show.png");
        PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[0].icon.toString())));
        // End of Password Deklariern
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        AnmeldenLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AnmeldenButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PassZeigen2 = new javax.swing.JCheckBox();
        PasswordField2 = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        VorNameField = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        UserNameField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        NachNameField = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        PassZeigen = new javax.swing.JCheckBox();
        PasswordField = new javax.swing.JPasswordField();
        jPanel17 = new javax.swing.JPanel();
        DatenSchutzBox = new javax.swing.JCheckBox();
        PassVergessen1 = new javax.swing.JLabel();
        PassVergessen = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        MaximierenPanel = new javax.swing.JPanel();
        max = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        VerkleinernPanel = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 702));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0,0,0,120)
        );
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/UserIcon.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ALWAIS'S-SPIEL");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HABEN SIE EIN KONTO?");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        AnmeldenLabel.setBackground(new java.awt.Color(0, 0, 0,0));
        AnmeldenLabel.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        AnmeldenLabel.setForeground(new java.awt.Color(51, 51, 51));
        AnmeldenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AnmeldenLabel.setText("ANMELDEN");
        AnmeldenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnmeldenLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AnmeldenLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AnmeldenLabelMouseExited(evt);
            }
        });
        jPanel12.add(AnmeldenLabel);

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 390, 670));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153,80));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnmeldenButton.setBackground(new java.awt.Color(0, 102, 153));
        AnmeldenButton.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        AnmeldenButton.setForeground(new java.awt.Color(255, 255, 255));
        AnmeldenButton.setText("WEITER");
        AnmeldenButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        AnmeldenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AnmeldenButton.setEnabled(false);
        AnmeldenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AnmeldenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnmeldenButtonActionPerformed(evt);
            }
        });
        jPanel4.add(AnmeldenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 200, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255,0));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "WILLKOMMEN ZURÜCK!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Traditional Arabic", 1, 48), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("WIR FREUEN UNS SEHR, SIE WIEDERZUSEHEN");
        jPanel8.add(jLabel8);

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 690, 190));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        PassZeigen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassZeigen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PassZeigen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/show.png"))); // NOI18N
        PassZeigen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassZeigen2ActionPerformed(evt);
            }
        });
        jPanel6.add(PassZeigen2);

        PasswordField2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        PasswordField2.setForeground(new java.awt.Color(0, 102, 153));
        PasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BESTÄTIGEN:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        PasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordField2MouseClicked(evt);
            }
        });
        PasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 440, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        VorNameField.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        VorNameField.setForeground(new java.awt.Color(0, 102, 153));
        VorNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VorNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VORNAME:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        VorNameField.setMinimumSize(new java.awt.Dimension(15, 45));
        VorNameField.setPreferredSize(new java.awt.Dimension(15, 45));
        VorNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VorNameFieldMouseClicked(evt);
            }
        });
        VorNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VorNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 310, 80));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        UserNameField.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        UserNameField.setForeground(new java.awt.Color(0, 102, 153));
        UserNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USERNAME: ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        UserNameField.setMinimumSize(new java.awt.Dimension(15, 45));
        UserNameField.setPreferredSize(new java.awt.Dimension(15, 45));
        UserNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserNameFieldMouseClicked(evt);
            }
        });
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 440, 80));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        NachNameField.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        NachNameField.setForeground(new java.awt.Color(0, 102, 153));
        NachNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NachNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NACHNAME:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        NachNameField.setMinimumSize(new java.awt.Dimension(15, 45));
        NachNameField.setPreferredSize(new java.awt.Dimension(15, 45));
        NachNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NachNameFieldMouseClicked(evt);
            }
        });
        NachNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NachNameFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NachNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NachNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 310, 80));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        PassZeigen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassZeigen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/show.png"))); // NOI18N
        PassZeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassZeigenActionPerformed(evt);
            }
        });
        jPanel16.add(PassZeigen);

        PasswordField.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 102, 153));
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PASSWORD:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Traditional Arabic", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseClicked(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 440, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));

        DatenSchutzBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatenSchutzBoxActionPerformed(evt);
            }
        });

        PassVergessen1.setBackground(new java.awt.Color(0, 0, 0,0));
        PassVergessen1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        PassVergessen1.setForeground(new java.awt.Color(51, 51, 51));
        PassVergessen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassVergessen1.setText("Ich habe die Service- und Datenschutzrichtlinien");
        PassVergessen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PassVergessen1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PassVergessen1MouseExited(evt);
            }
        });

        PassVergessen.setBackground(new java.awt.Color(0, 0, 0,0));
        PassVergessen.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        PassVergessen.setForeground(new java.awt.Color(51, 51, 51));
        PassVergessen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassVergessen.setText("von ALWAIS'S-SPIEL gelesen und bin damit einverstanden");
        PassVergessen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PassVergessenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PassVergessenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(DatenSchutzBox, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassVergessen1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PassVergessen, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PassVergessen1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DatenSchutzBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassVergessen)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 440, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 870, 670));

        jPanel47.setBackground(new java.awt.Color(0, 0, 0));
        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        MaximierenPanel.setBackground(new java.awt.Color(255, 255, 255));
        MaximierenPanel.setEnabled(false);
        MaximierenPanel.setLayout(new java.awt.GridLayout(1, 0));

        max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/verkleinernicon.png"))); // NOI18N
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });
        MaximierenPanel.add(max);

        ExitPanel.setBackground(new java.awt.Color(255, 255, 255));
        ExitPanel.setLayout(new java.awt.GridLayout(1, 0));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/exiticon.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });
        ExitPanel.add(exit);

        VerkleinernPanel.setBackground(new java.awt.Color(255, 255, 255));
        VerkleinernPanel.setLayout(new java.awt.GridLayout(1, 0));

        min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/minusicon.png"))); // NOI18N
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        VerkleinernPanel.add(min);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/conect422.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("CONNECT 4");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addComponent(ExitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VerkleinernPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MaximierenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 938, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(VerkleinernPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MaximierenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/KontoerstellenHintergrund.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1260, 702));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnmeldenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnmeldenLabelMouseClicked
        // TODO add your handling code here:
        anmelden = new AnmeldenFrame();
        anmelden.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AnmeldenLabelMouseClicked

    private void AnmeldenLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnmeldenLabelMouseEntered
        // TODO add your handling code here:
        AnmeldenLabel.setForeground(new java.awt.Color(0, 153, 255));
    }//GEN-LAST:event_AnmeldenLabelMouseEntered

    private void AnmeldenLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnmeldenLabelMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        AnmeldenLabel.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_AnmeldenLabelMouseExited

    private void AnmeldenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnmeldenButtonActionPerformed

        try {

            String nachname = NachNameField.getText();
            String vorname = VorNameField.getText();
            String username = UserNameField.getText();
            String password = PasswordField.getText();

            ss.setString(1, nachname);
            ss.setString(2, vorname);
            ss.setString(3, username);
            ss.setString(4, password);

            NachNameField.setText("");
            VorNameField.setText("");
            UserNameField.setText("");
            PasswordField.setText("");
            PasswordField2.setText("");
            updateStatement = ss.executeUpdate();
            if (updateStatement > 0) {
                anmelden = new AnmeldenFrame();
                anmelden.setVisible(true);
                JOptionPane.showMessageDialog(null, "ERFOLGREICH GESPEICHERT", "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "CONNECT 4", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_AnmeldenButtonActionPerformed

    private void PassVergessenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassVergessenMouseEntered

    }//GEN-LAST:event_PassVergessenMouseEntered

    private void PassVergessenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassVergessenMouseExited

    }//GEN-LAST:event_PassVergessenMouseExited

    private void PasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordField2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField2MouseClicked

    private void PasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField2ActionPerformed


    }//GEN-LAST:event_PasswordField2ActionPerformed

    private void PassZeigen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassZeigen2ActionPerformed
        // TODO add your handling code here:

        if (PassZeigen2.isSelected()) {
            PasswordField2.setEchoChar((char) 0);
            PassZeigen2.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[1].icon.toString())));
        } else {
            PasswordField2.setEchoChar('*');
            PassZeigen2.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[0].icon.toString())));
        }
    }//GEN-LAST:event_PassZeigen2ActionPerformed

    private void VorNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VorNameFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_VorNameFieldMouseClicked

    private void VorNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VorNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VorNameFieldActionPerformed

    private void UserNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNameFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFieldMouseClicked

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFieldActionPerformed

    private void NachNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NachNameFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NachNameFieldMouseClicked

    private void NachNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NachNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NachNameFieldActionPerformed

    private void PassZeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassZeigenActionPerformed
        // TODO add your handling code here:
        if (PassZeigen.isSelected()) {
            PasswordField.setEchoChar((char) 0);
            PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[1].icon.toString())));
        } else {
            PasswordField.setEchoChar('*');
            PassZeigen.setIcon(new javax.swing.ImageIcon(getClass().getResource(PassZeigerIcon[0].icon.toString())));
        }
    }//GEN-LAST:event_PassZeigenActionPerformed

    private void PasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldMouseClicked

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void PassVergessen1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassVergessen1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PassVergessen1MouseEntered

    private void PassVergessen1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassVergessen1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PassVergessen1MouseExited

    private void DatenSchutzBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatenSchutzBoxActionPerformed
        // TODO add your handling code here:
        if (DatenSchutzBox.isSelected()) {
            AnmeldenButton.setEnabled(true);
        } else {
            AnmeldenButton.setEnabled(false);
        }
    }//GEN-LAST:event_DatenSchutzBoxActionPerformed

    private void maxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseClicked
        // TODO add your handling code here:
        /*  if (getSize().width > 1260 && getSize().height > 702) {
            Verkleinern();
        } else {
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        */
    }//GEN-LAST:event_maxMouseClicked

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[0].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[2].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[4].icon.toString())));
        MaximierenPanel.setBackground(Color.GREEN);
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        MaximierenPanel.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_maxMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        frame = new JFrame("EXIT");

        if (JOptionPane.showConfirmDialog(frame, "Bestätigen Sie, ob Sie beenden möchten", "CONNECT 4",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[0].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[2].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[4].icon.toString())));
        ExitPanel.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        ExitPanel.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_exitMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_minMouseClicked

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[0].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[2].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[4].icon.toString())));
        VerkleinernPanel.setBackground(new java.awt.Color(255, 204, 0));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        // TODO add your handling code here:
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[1].icon.toString())));
        min.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[3].icon.toString())));
        max.setIcon(new javax.swing.ImageIcon(getClass().getResource(EMM[5].icon.toString())));
        VerkleinernPanel.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_minMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KontoErstellenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KontoErstellenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KontoErstellenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KontoErstellenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KontoErstellenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnmeldenButton;
    private javax.swing.JLabel AnmeldenLabel;
    private javax.swing.JCheckBox DatenSchutzBox;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel MaximierenPanel;
    private javax.swing.JTextField NachNameField;
    private javax.swing.JLabel PassVergessen;
    private javax.swing.JLabel PassVergessen1;
    private javax.swing.JCheckBox PassZeigen;
    private javax.swing.JCheckBox PassZeigen2;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JPanel VerkleinernPanel;
    private javax.swing.JTextField VorNameField;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel max;
    private javax.swing.JLabel min;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(window.icon.toString())));
    }
}
